# Generated by Django 5.2.4 on 2025-08-16 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelModerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_owner', models.BooleanField(default=False, verbose_name='Владелец канала')),
                ('can_edit', models.BooleanField(default=True, verbose_name='Может редактировать')),
                ('can_delete', models.BooleanField(default=False, verbose_name='Может удалять')),
                ('can_manage_moderators', models.BooleanField(default=False, verbose_name='Может управлять модераторами')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderators', to='parser.telegramchannel', verbose_name='Канал')),
            ],
            options={
                'verbose_name': 'Модератор канала',
                'verbose_name_plural': 'Модераторы каналов',
                'db_table': 'channel_moderators',
            },
        ),
    ]
