# Generated by Django 5.2.4 on 2025-08-16 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0002_channelmoderator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmoderator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderated_channels', to=settings.AUTH_USER_MODEL, verbose_name='Модератор'),
        ),
        migrations.AlterUniqueTogether(
            name='channelmoderator',
            unique_together={('user', 'channel')},
        ),
    ]
